version: '2'
volumes:
   jdk-builder-volume:
services:
  app:
    build:
      context: app
    expose:
      - "50051"

  envoy:
    image: "envoyproxy/envoy:latest"
    ports:
      - "8080:80"
      - "8081:8001"
    command: /usr/local/bin/envoy -c /etc/envoy/config/envoy.json --service-cluster clstr --service-node nd
    volumes:
      - ./envoy/:/etc/envoy/config/:ro # /etc/envoy/config/envoy.json
      - ./proto/:/etc/envoy/proto/:ro # /etc/envoy/proto/descriptor_set.pb
